/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{

	SIT("[action][SIT]",1500),
	CHAT("[action][CHAT]",1500),
	PAUSE("[action][PAUSE]",1500),
	END("[action][END]",1500),
	RESUME("[action][RESUME]",1500),
	PLAYERS("[action][PLAYERS]",1500),
	OPTIONS("[action][OPTIONS]",1500),
	BETVALUE("[action][BETVALUE]",1500),
	RAISE("[action][RAISE]",1500),
	BET("[action][BET]",1500),
	FOLD("[action][FOLD]",1500),
	CHECK("[action][CHECK]",1500);




private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
