/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{

	PLAYERS("[action][PLAYERS]",1500),
	OPTIONS("[action][OPTIONS]",1500),
	RAISE("[action][RAISE]",0),
	BET("[action][BET]",0),
	FOLD("[action][FOLD]",0),
	CHECK("[action][CHECK]",0),
	ALL_IN("[action][ALL_IN]",1500 ),
	DUPLICATE("[action][DUPL]",1500 ),
	MIN("[action][MIN]",1500 ),
	PAUSE("[action][PAUSE]",0),
	END("[action][END]",0),
	RESUME("[action][RESUME]",0),
	START("[action][START]", 0),
	CHATON("[action][CHATON]", 0),
	CHATOFF("[action][CHATOFF]", 0);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
