/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{

	PLAYERS("[action][PLAYERS]",0),
	OPTIONS("[action][OPTIONS]",0),
	RAISE("[action][RAISE]",0),
	BET("[action][BET]",0),
	FOLD("[action][FOLD]",0),
	CHECK("[action][CHECK]",0),
	ALL_IN("[action][ALL_IN]",0 ),
	DUPLICATE("[action][DUPL]",0 ),
	MIN("[action][MIN]",0 ),
	CHAT("[action][CHAT]",0),
	PAUSE("[action][PAUSE]",0),
	END("[action][END]",0),
	RESUME("[action][RESUME]",0);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
